### ISSUE TITLE
Problems running the examples

### ISSUE THREAD

**Issue by krabbenprgr** [borrrden/Fido2Net#3]
I get an error running the examples:
`DllNotFoundException: Unable to load DLL 'fido2' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)`
Before execution, i build the native dependencies via the provided script: build_deps.ps1. But there is no fido2.dll file generated?

Any ideas?

Thanks in advance

**Comment by gunjanai** [comment]
You need to download a libfido2 release from Yubico's page - https://developers.yubico.com/libfido2/Releases/
And copy all of the contents of this folder "C:\Users\Downloads\libfido2-1.12.0-win.zip\libfido2-1.12.0-win\Win64\Release\v143\dynamic" to your project's bin folder i.e. - "C:\Users\Fido2Net-master\demoform\bin\Debug\net5.0-windows"

This will work.

Try building the solution in Visual Studio.
